ci: compile for dist, remove node_modules
* Use ncc to create `dist/index.js`, as recommended in:
  https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github
* Remove `node_modules` from repo
* Point action.yml at `dist/index.js`
* Add a job to `workflows/test.yml` to ensure `dist/index.js` is updated.
* Remove unused `express` and `mocha` dependencies

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,10 +8,37 @@ on:
   workflow_dispatch:
 
 jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - run: npm ci
+      - run: npm run build
+      - name: Confirm new build included in commit
+        # language=bash
+        run: |
+          # Confirm that the dist was built, and changes included in the commit
+          if [ $(git status --porcelain dist/index.js | wc -l) -eq "1" ]; then
+            echo "::error title=Build not committed::Running 'npm run build' changes 'dist/index.js' - build locally and add changes to commit."
+            exit 1
+          fi
+
+  direct-from-repository-test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Confirm execution without install/build
+        uses: ./
+        with:
+          name: "Successful cucumber report direct from repository"
+          access-token: ${{ secrets.GITHUB_TOKEN }}
+          path: "**/cucumber-report.json" # This committed report should be a success
+
   ubuntu-action-tests:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
+      - uses: actions/checkout@v3
+      - run: npm ci
       - run: npm run cucumber || true
       - run: npm run cucumber-ok || true
       - run: npm run cucumber-undefined || true
